// Code generated by goctl. DO NOT EDIT.
package types

type ErrorInfo struct {
	ErrorCode int64  `json:"errno"` //错误码
	ErrorMsg  string `json:"error"` //错误信息
}

type ErrorResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
}

type PdfInfo struct {
	FileUrl   string `json:"file_url"`  //文件url
	ObjecktId string `json:"object_id"` //对象id
}

type TokenErrorInfo struct {
	ErrorCode int64  `json:"code"` //错误码
	ErrorMsg  string `json:"msg"`  //错误信息
}

type UrlToPdfRequest struct {
	Url             string  `json:"url"`                                              //老师id
	Delay           int64   `json:"delay,optional,default=0"`                         //延迟时间
	Scale           float64 `json:"scale,optional,default=1"`                         //老师手机号
	ObjectKey       string  `json:"object_key,default=output"`                        //object key 不能以“/”开头
	HeaderTokenName string  `json:"header_token_name,optional,default=Authorization"` //header token 名称
	Token           string  `json:"jwt_token,optional"`                               //url验证token
	IsSign          bool    `json:"is_sign,optional,default=false"`                   //是否需要签名
	SignExpire      int64   `json:"sign_expire,optional,default=300"`                 //签名有效期,默认5分钟
}

type UrlToPdfResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"` //错误信息
	Data      PdfInfo   `json:"data"`       //老师服务列表数据
}
